# Generated by Django 4.0.10 on 2023-03-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_objects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objects',
        ),
    ]
