# Generated by Django 4.0.10 on 2023-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('objectId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detected', models.CharField(max_length=20)),
            ],
        ),
    ]
