# Generated by Django 4.0.10 on 2023-03-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_video_caption_alter_video_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objects',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
